import cudaq

cudaq.set_target('nvidia')

@cudaq.kernel
def bell(N:int):
    qubits=cudaq.qvector(N)

    h(qubits[0])
    x.ctrl(qubits[0], qubits[1])

    mz(qubits)

print(cudaq.draw(bell,2))
# Sample the state generated by bell
# shots_count: the number of kernel executions. Default is 1000
counts = cudaq.sample(bell, 2, shots_count=10000) 

# Print to standard out
print(counts)

# Fine-grained access to the bits and counts 
for bits, count in counts.items():
    print('Observed: {}, {}'.format(bits, count))

print('Most probable bit string: ', counts.most_probable())  